info:
  component: Hystrix Dashboard
  
endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true

server:
  port: 7979

logging:
  level:
    ROOT: INFO
    org.springframework.web: DEBUG

eureka:
  instance:
    virtualHostName: ${spring.application.name}
    leaseRenewalIntervalInSeconds: 10
    hostname: ${CF_INSTANCE_IP:192.168.109.2}
    nonSecurePort: ${CF_INSTANCE_PORT:${PORT:${server.port:7979}}}
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVICE_URL:http://localhost:8761}/eureka/
